name: OWASP Dependency Check

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]
  schedule:
    - cron: "0 0 * * 0" # Chạy hàng tuần vào nửa đêm Chủ nhật

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci

      - name: Install OWASP Dependency Check
        run: npm install --save-dev @owasp/dependency-check

      - name: Run OWASP Dependency Check
        run: npx dependency-check ./package.json --failOn CVSS7

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-report
          path: ./reports/dependency-check-report.xml
